---
title: Upgrade/downgrade Power Automate
description: Guidelines for upgrading or downgrading Power Automate for desktop and the machine runtime application, as well as addressing backward and forward compatibility concerns.
author: PetrosFeleskouras
ms.subservice: desktop-flow
ms.topic: how-to
ms.date: 03/05/2025
ms.author: pefelesk
ms.reviewer: 
contributors:
- PetrosFeleskouras
search.audienceType: 
  - flowmaker
  - admin
---
# Upgrade/downgrade Power Automate

This article offers guidance on upgrading or downgrading Power Automate for desktop and the machine runtime app, and addresses compatibility concerns.

## Upgrade Power Automate 

Learn how to [install Power Automate](../install.md) and [install Power Automate silently](../install-silently.md).  

[Manage manual updates and update notifications](../console.md#update-power-automate-for-desktop) through the Power Automate for desktop Console and machine-runtime app.  

To prevent users from manually updating Power Automate and receiving update notifications, use [this registry entry](../governance.md#prevent-users-manually-updating-power-automate-for-desktop). 

### Backward compatibility

Power Automate maintains backwards compatibility, ensuring that users who upgrade to the latest version retain functionality and access to their previous work. The newer versions of the software are designed to operate seamlessly with desktop flows created with older versions. 

**Desktop flows** are stored in the **Process** Dataverse table and **remain unaffected by software upgrades**.  

Each desktop flow is associated with the version of Power Automate for desktop with which it was created or modified. For a desktop flow version to be updated, it must be edited and re-saved with a different software version.  

> [!NOTE]
> Updating the flow properties does not alter the flow version.

To determine the version associated with a desktop flow:

1. Sign in to the [Power Automate portal](https://make.powerautomate.com).
1. Select your **Environment**.
1. Select **Tables** from the left navigation pane.
1. Change the table filter to **All** and search for the **Process** table.
1. Open the Process table and filter by **Category = Desktop Flow**.

The **clientversion** property in the **Metadata** column shows the last Power Automate for desktop version used to save the flow. 

    :::image type="content" source="media/reduce-flow-size/remove-ui-element-screenshots.png" alt-text="Screenshot of a solution containing desktop flow objects." lightbox="media/reduce-flow-size/remove-ui-element-screenshots.png":::

## Downgrade Power Automate  

Downgrading Power Automate is not supported, and Microsoft does not provide direct download links for older versions of Power Automate for desktop. The latest version is always installed when you download using an [MSI installer](../install.md#install-power-automate-using-the-msi-installer) or from [Microsoft Store](../install.md#install-power-automate-from-microsoft-store). 

If you require access to an older version for business continuity purposes, please contact Microsoft Support. 

> [!NOTE]
> To downgrade Power Automate, you are required to uninstall the current version before installing the desired one.

###Forward compatibility

Forward compatibility with Power Automate is not guaranteed. Updates, such as new features, product enhancements, and fixed functionalities, may not be supported by the older version, leading to potential compatibility issues. 

Flows created using a newer version of Power Automate might not function correctly if you try to edit or run them with an older version of the software.  
Such a scenario may result in the following error message: 
- > `This flow has been generated by a newer Power Automate version than the one currently installed. Download and install the latest version of Power Automate and try again.`
